### ISSUE TITLE
Leaving the app and coming back freezes the screen 

### ISSUE THREAD

**Issue by chinajuice** [michal4132/cspot_vita#10]
Leaving the app and coming back freezes the image and it never opens the app properly, using version 0.26 and firmware ver 3.60
![image](https://user-images.githubusercontent.com/119765284/205466533-ca52f50e-d57f-4833-925d-9c840750ce73.jpg)

**Comment by chinajuice** [comment]
[log.txt](https://github.com/michal4132/cspot_vita/files/10147537/log.txt)

**Comment by michal4132** [comment]
Should be fixed in 0.2.7
