### ISSUE TITLE
Audio stop working after 2-3 songs

### ISSUE THREAD

**Issue by PTHyperdrive** [michal4132/cspot_vita#13]
My psvita stop music with AudioChunkManager.cpp freeze. Inconsistently freeze audio, sometime it will not happen. If you have this problem maybe you'll understand why it bugging out. My suggestion for this bug is after each song restart the AudioChunkManager, on android every song will restart audiosink function. Hope this will give you some idea for fixing it

**Comment by michal4132** [comment]
Try new 0.2.8 release. It should resolve your issue or at least reduce frequency of occurrence.

**Comment by PTHyperdrive** [comment]
Seem like it been fix, just right now :)))). Let's see if I'd see any bugs then I'll issue for building this project far more perfect

**Comment by michal4132** [comment]
Fixed in: https://github.com/michal4132/cspot_vita/commit/ade7c3fe8801270e556c6bb07e4d7bb576e663e3.
Released as 0.2.9
