### ISSUE TITLE
Music browsing?

### ISSUE THREAD

**Issue by chinajuice** [michal4132/cspot_vita#9]
Is it implemented? Whenever I click the music icon I get error C2-12828-1

**Comment by michal4132** [comment]
Which cspot_vita and firmware version are using? Can you provide log file located in: `ux0:data/cspot/log.txt`?

**Comment by chinajuice** [comment]
Oh I was using the build from the vita homebrew browser, version 0.22 I think, I updated the vpk to  0.26 and now it shows my playlists, but search button prompts nothing, my firmware ver. Is 3.60, using enso, amazing work, thank you for releasing this

**Comment by michal4132** [comment]
The search button is not yet implemented.
